version: "3.8"

services:
  api:
    restart: always
    build: .
    ports:
      - "7100:7100"
    volumes:
      - .:/code
    command:
      - "uvicorn"
      - "main:app"
      - "--host=0.0.0.0"
      - "--port=7100"
      - "--reload"